### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by robksawyer** [robksawyer/nextjs-phaser#1]
```
ReferenceError: navigator is not defined
    at init (/Users/robksawyer/Sites/FOMOLOL/1_CLIENTS/NFTGenius/nextjs-phaser/node_modules/phaser/src/device/OS.js:69:14)
    at Object.<anonymous> (/Users/robksawyer/Sites/FOMOLOL/1_CLIENTS/NFTGenius/nextjs-phaser/node_modules/phaser/src/device/OS.js:186:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/robksawyer/Sites/FOMOLOL/1_CLIENTS/NFTGenius/nextjs-phaser/node_modules/phaser/src/device/index.js:32:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/Users/robksawyer/Sites/FOMOLOL/1_CLIENTS/NFTGenius/nextjs-phaser/node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)
    at ChildProcessWorker._onExit (/Users/robksawyer/Sites/FOMOLOL/1_CLIENTS/NFTGenius/nextjs-phaser/node_modules/jest-worker/build/workers/ChildProcessWorker.js:275:12)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  type: 'WorkerError'
}
```

**Comment by robksawyer** [comment]
Fixed this with the following.

```
const Phaser = React.useMemo(() => {
    if (typeof window !== 'undefined' && typeof window.navigator !== 'undefined') {
      return require('phaser/src/phaser')
    }
  },[]);
```

**Comment by gatlee21** [comment]
Commenting in April 2023 to say that @robksawyer's solution still works
